
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='ggg',
    version='0.1.2',
    python_requires='==3.*,>=3.8.0',
    author='Nick',
    author_email='n@nickcheng.com',
    packages=['ggg', 'ggg.mylib'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click==7.*,>=7.0.0', 'colorama==0.*,>=0.4.3', 'inquirer==2.*,>=2.6.3', 'ipykernel==5.*,>=5.1.4', 'jupyter==1.*,>=1.0.0', 'toml==0.*,>=0.10.1'],
    extras_require={"dev": ["pylint==2.*,>=2.4.4", "pytest==5.*,>=5.2.0"]},
    entry_points={
        'console_scripts': ['ggg=ggg.app:cli'],
    },
)
